name: Benchmarks

on:
  schedule:
    - cron: '0 0 * * *'
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup scala
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: "openjdk@1.11"
      - name: Run benchmarks
        run: sbt benchmarks/jmh:run -i 1 -wi 1 -f1 -t1 .SampleSpelBenchmark -rf csv
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jmh-result.csv
          path: engine/benchmarks/jmh-result.csv