name: Benchmarks

on:
  schedule:
    - cron: '0 0 * * *'
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Cache ivy packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-ivy2-${{ hashFiles('**/*.sbt') }}
          restore-keys: ${{ runner.os }}-sbt
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: "openjdk@1.11"
      - name: Run benchmarks
        shell: bash
        run: ./ciRunSbt.sh benchmarks/jmh:run -i 1 -wi 1 -f1 -t1 .SampleSpelBenchmarkForTest -rf csv
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jmh-result.csv
          path: engine/benchmarks/jmh-result.csv
